[package]
name = "project_euler"
version = "0.1.0"
edition = "2024"

[dependencies]
bit-vec = "0.8.0"
dashu = "0.4.2"
num-traits = "0.2.19"
paste = "1.0.15"
permutohedron = "0.2.4"
rand = "0.9.0"

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
